FROM golang:1.26-alpine

WORKDIR /app
RUN apk add --no-cache git ca-certificates chromium nss freetype harfbuzz font-noto ttf-freefont && \
    go install github.com/air-verse/air@v1.61.7 && \
    go install github.com/pressly/goose/v3/cmd/goose@v3.24.1
ENV CHROME_PATH=/usr/bin/chromium

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
