package service

import (
	"bytes"
	"html/template"
	"strings"

	"github.com/erman-ai/erman-ai/internal/model"
)

type legalScanPDFLabels struct {
	Title        string
	CheckedSite  string
	RisksFound   string
	FixedFines   string
	PagesChecked string
	Checks       string
	Article      string
	Fine         string
	HowToFix     string
	NoRisk       string
	High         string
	Medium       string
	Low          string
	Documents    string
	FoundData    string
	Disclaimer   string
}

type legalScanPDFCheck struct {
	Title       string
	Severity    string
	SeverityCSS string
	Explanation string
	Article     string
	FineText    string
	HowToFix    string
	PageURLs    []string
	FoundData   []string
}

type legalScanPDFData struct {
	LangAttr     string
	Labels       legalScanPDFLabels
	URL          string
	RisksCount   int
	FineMax      string
	PagesFetched int
	Checks       []legalScanPDFCheck
	IndustryNote string
	Disclaimer   string
}

func GenerateLegalScanPDF(input model.LegalScanInput, output model.LegalScanOutput, locale string) ([]byte, error) {
	if locale != "en" {
		locale = "ru"
	}
	html, err := renderLegalScanReportHTML(input, output, locale)
	if err != nil {
		return nil, err
	}
	return htmlToPDF(html)
}

func renderLegalScanReportHTML(input model.LegalScanInput, output model.LegalScanOutput, locale string) (string, error) {
	labels := legalScanPDFLabelsForLocale(locale)
	checks := make([]legalScanPDFCheck, 0, len(output.Layer1.Checklist)+len(output.Risks))
	shownRiskIDs := map[string]struct{}{}
	for _, item := range output.Layer1.Checklist {
		check := legalScanPDFCheck{
			Title:       item.Label,
			Severity:    labels.NoRisk,
			SeverityCSS: "none",
			Explanation: item.Evidence,
			PageURLs:    item.PageURLs,
			FoundData:   item.FoundData,
		}
		if strings.TrimSpace(check.Explanation) == "" {
			check.Explanation = labels.NoRisk
		}
		if item.Status == "risk" {
			if risk, ok := riskForChecklistItem(item.Key, output.Risks); ok {
				shownRiskIDs[risk.RiskID] = struct{}{}
				check.Title = risk.Title
				check.Severity = legalScanSeverityLabel(risk.Severity, labels)
				check.SeverityCSS = risk.Severity
				check.Explanation = risk.Explanation
				check.Article = risk.Article
				check.FineText = risk.FineText
				check.HowToFix = risk.HowToFix
				check.PageURLs = firstNonEmptyStrings(risk.PageURLs, item.PageURLs)
				check.FoundData = firstNonEmptyStrings(risk.FoundData, item.FoundData)
			} else {
				check.Severity = labels.Medium
				check.SeverityCSS = "medium"
			}
		}
		checks = append(checks, check)
	}
	for _, risk := range output.Risks {
		if _, ok := shownRiskIDs[risk.RiskID]; ok {
			continue
		}
		checks = append(checks, legalScanPDFCheck{
			Title:       risk.Title,
			Severity:    legalScanSeverityLabel(risk.Severity, labels),
			SeverityCSS: risk.Severity,
			Explanation: risk.Explanation,
			Article:     risk.Article,
			FineText:    risk.FineText,
			HowToFix:    risk.HowToFix,
			PageURLs:    risk.PageURLs,
			FoundData:   risk.FoundData,
		})
	}

	pagesFetched := 1
	if output.Layer1.Crawl != nil && output.Layer1.Crawl.PagesFetched > 0 {
		pagesFetched = output.Layer1.Crawl.PagesFetched
	}
	url := output.Layer1.FinalURL
	if url == "" {
		url = input.URL
	}
	fineMax := "—"
	if output.Summary.FineMaxTotal > 0 {
		fineMax = formatLocaleMoney(float64(output.Summary.FineMaxTotal), locale)
	}

	data := legalScanPDFData{
		LangAttr:     locale,
		Labels:       labels,
		URL:          url,
		RisksCount:   output.Summary.RisksCount,
		FineMax:      fineMax,
		PagesFetched: pagesFetched,
		Checks:       checks,
		IndustryNote: output.IndustryNote,
		Disclaimer:   output.Disclaimer,
	}
	if data.Disclaimer == "" {
		data.Disclaimer = legalScanDisclaimerRU
	}

	tmpl, err := template.New("legal-scan-report").Parse(legalScanReportHTMLTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func legalScanPDFLabelsForLocale(locale string) legalScanPDFLabels {
	if locale == "en" {
		return legalScanPDFLabels{
			Title: "Legal Site Scan", CheckedSite: "Checked site", RisksFound: "Risks found",
			FixedFines: "Potential fixed fines", PagesChecked: "Pages checked", Checks: "Check results",
			Article: "Article", Fine: "Fine", HowToFix: "How to fix", NoRisk: "no risk",
			High: "high", Medium: "medium", Low: "low", Documents: "Links", FoundData: "Found data",
			Disclaimer: "Generated by Erman AI. This report is informational and is not legal advice.",
		}
	}
	return legalScanPDFLabels{
		Title: "Legal-скан сайта", CheckedSite: "Проверенный сайт", RisksFound: "Рисков найдено",
		FixedFines: "Потенциальные фикс. штрафы", PagesChecked: "Страниц проверено", Checks: "Результаты проверки",
		Article: "Статья", Fine: "Штраф", HowToFix: "Как исправить", NoRisk: "нет риска",
		High: "высокий", Medium: "средний", Low: "низкий", Documents: "Ссылки", FoundData: "Найденные данные",
		Disclaimer: "Сгенерировано Erman AI. Отчёт носит информационный характер и не является юридической консультацией.",
	}
}

func legalScanSeverityLabel(severity string, labels legalScanPDFLabels) string {
	switch severity {
	case "high":
		return labels.High
	case "medium":
		return labels.Medium
	case "low":
		return labels.Low
	default:
		return labels.NoRisk
	}
}

func riskForChecklistItem(key string, risks []model.LegalScanRiskItem) (model.LegalScanRiskItem, bool) {
	riskIDs := map[string][]string{
		"ssl":     {"no_ssl"},
		"privacy": {"no_privacy_policy"},
		"cookie":  {"no_cookie_banner"},
		"consent": {"no_consent"},
		"req":     {"no_requisites"},
		"offer":   {"no_offer"},
		"admark":  {"no_ad_marking"},
	}
	for _, id := range riskIDs[key] {
		for _, risk := range risks {
			if risk.RiskID == id {
				return risk, true
			}
		}
	}
	return model.LegalScanRiskItem{}, false
}

func firstNonEmptyStrings(primary, fallback []string) []string {
	if len(primary) > 0 {
		return primary
	}
	return fallback
}

const legalScanReportHTMLTemplate = `<!DOCTYPE html>
<html lang="{{.LangAttr}}">
<head>
  <meta charset="UTF-8" />
  <title>{{.Labels.Title}} — Erman AI</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; font-size: 13px; line-height: 1.5; color: #1a1a1a; background: #f3f2ef; padding: 24px; }
    .page { max-width: 900px; margin: 0 auto; }
    .card { background: #fff; border: 1px solid #e8e7e3; border-radius: 12px; padding: 32px; margin-bottom: 16px; }
    .brand { display: flex; align-items: center; gap: 10px; margin-bottom: 24px; }
    .brand-mark { width: 28px; height: 28px; border-radius: 6px; background: #1a1a1a; color: #fff; display: flex; align-items: center; justify-content: center; font-weight: 600; }
    .brand-name { font-size: 14px; font-weight: 500; }
    h1 { font-size: 22px; margin-bottom: 8px; }
    .muted { color: #5f5e5a; }
    .small { font-size: 12px; color: #888780; }
    .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 24px 0; }
    .metric { border: 1px solid #e8e7e3; border-radius: 10px; background: #f8f8f7; padding: 14px; }
    .metric-label { font-size: 10px; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: #888780; margin-bottom: 8px; }
    .metric-value { font-size: 22px; font-weight: 600; }
    .section-title { font-size: 10px; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: #888780; margin: 28px 0 12px; }
    .check { border: 1px solid #e8e7e3; border-left: 4px solid #d3d1c7; border-radius: 10px; padding: 14px 16px; margin-bottom: 10px; background: #fff; page-break-inside: avoid; }
    .check.none { border-left-color: #3b6d11; }
    .check.high { border-left-color: #e0492f; }
    .check.medium { border-left-color: #f0a728; }
    .check.low { border-left-color: #9aa0a6; }
    .check-head { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
    .check-title { font-weight: 600; font-size: 14px; }
    .badge { display: inline-block; border: 1px solid #e8e7e3; border-radius: 999px; padding: 2px 8px; font-size: 11px; color: #5f5e5a; }
    .badge.none { color: #3b6d11; background: #eaf3de; border-color: #c5ddb0; }
    .badge.high { color: #b42318; background: #fef3f2; border-color: #fbdcd8; }
    .badge.medium { color: #b25e09; background: #fffaeb; border-color: #fbe6c2; }
    .badge.low { color: #5f5e5a; background: #f8f8f7; }
    .chips { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 8px; }
    .chip { border: 1px solid #e8e7e3; border-radius: 6px; background: #f8f8f7; padding: 3px 7px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; }
    ul { margin: 8px 0 0 18px; }
    a { color: #185fa5; word-break: break-all; }
    .fix { margin-top: 8px; color: #1a1a1a; }
    .footer { text-align: center; font-size: 12px; color: #888780; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="page">
    <div class="card">
      <div class="brand"><div class="brand-mark">E</div><span class="brand-name">Erman AI</span></div>
      <h1>{{.Labels.Title}}</h1>
      <p class="muted">{{.Labels.CheckedSite}}: {{.URL}}</p>
      <div class="grid">
        <div class="metric"><div class="metric-label">{{.Labels.RisksFound}}</div><div class="metric-value">{{.RisksCount}}</div></div>
        <div class="metric"><div class="metric-label">{{.Labels.FixedFines}}</div><div class="metric-value">{{.FineMax}}</div></div>
        <div class="metric"><div class="metric-label">{{.Labels.PagesChecked}}</div><div class="metric-value">{{.PagesFetched}}</div></div>
      </div>
      <div class="section-title">{{.Labels.Checks}}</div>
      {{range .Checks}}
        <div class="check {{.SeverityCSS}}">
          <div class="check-head">
            <span class="check-title">{{.Title}}</span>
            <span class="badge {{.SeverityCSS}}">{{.Severity}}</span>
          </div>
          <p class="muted">{{.Explanation}}</p>
          {{if .FoundData}}
            <div class="chips">{{range .FoundData}}<span class="chip">{{.}}</span>{{end}}</div>
          {{end}}
          {{if .PageURLs}}
            <p class="small" style="margin-top:8px;">{{$.Labels.Documents}}</p>
            <ul>{{range .PageURLs}}<li><a href="{{.}}">{{.}}</a></li>{{end}}</ul>
          {{end}}
          {{if .Article}}<p class="small" style="margin-top:8px;">{{$.Labels.Article}}: {{.Article}}</p>{{end}}
          {{if .FineText}}<p class="small">{{$.Labels.Fine}}: {{.FineText}}</p>{{end}}
          {{if .HowToFix}}<p class="fix">✓ {{.HowToFix}}</p>{{end}}
        </div>
      {{end}}
      {{if .IndustryNote}}<p class="muted" style="margin-top:16px;">{{.IndustryNote}}</p>{{end}}
      <p class="footer">{{.Disclaimer}}</p>
    </div>
  </div>
</body>
</html>`
