import type { CalculatorProcessTemplate, CalculatorSector, LocalizedText } from "./types";

const L = (ru: string, en: string): LocalizedText => ({ ru, en });

const S = (
  opRu: string,
  opEn: string,
  execRu: string,
  execEn: string,
  minutes: number,
  rate: number
) => ({
  operation: L(opRu, opEn),
  executor: L(execRu, execEn),
  minutes_per_unit: minutes,
  rate_rub_per_min: rate,
});

const T = (
  id: string,
  nameRu: string,
  nameEn: string,
  descRu: string,
  descEn: string,
  processRu: string,
  processEn: string,
  steps: ReturnType<typeof S>[],
  units: number,
  autoPct: number,
  errPct: number,
  throughput: number
): CalculatorProcessTemplate => ({
  id,
  name: L(nameRu, nameEn),
  description: L(descRu, descEn),
  process_name: L(processRu, processEn),
  process_steps: steps,
  units_per_month: units,
  automation_pct: autoPct,
  error_rate_before_pct: errPct,
  throughput_before_per_day: throughput,
});

export const CALCULATOR_SECTORS: CalculatorSector[] = [
  {
    id: "digital_marketing",
    name: L("Digital-маркетинг", "Digital marketing"),
    templates: [
      T(
        "dm_leads",
        "Обработка лидов с рекламы",
        "Ad lead processing",
        "Квалификация и передача лидов из рекламных каналов в CRM",
        "Qualify and route ad leads into CRM",
        "Обработка лидов с сайта и рекламы",
        "Website and ad lead processing",
        [
          S("Первичная квалификация", "Initial qualification", "Маркетолог", "Marketer", 4, 18),
          S("Проверка дублей в CRM", "Duplicate check in CRM", "Оператор", "Operator", 2, 14),
          S("Назначение менеджеру", "Assign to sales rep", "CRM-админ", "CRM admin", 1, 16),
          S("Первое касание", "First touch outreach", "Менеджер", "Sales rep", 6, 33),
        ],
        1200,
        75,
        8,
        25
      ),
      T(
        "dm_report",
        "Еженедельный отчёт по кампаниям",
        "Weekly campaign report",
        "Сбор данных из кабинетов и подготовка отчёта клиенту",
        "Pull ad platform data and prepare client report",
        "Еженедельный отчёт по рекламным кампаниям",
        "Weekly advertising campaign report",
        [
          S("Выгрузка из кабинетов", "Export from ad platforms", "Аналитик", "Analyst", 25, 20),
          S("Свод в таблицу", "Consolidate spreadsheet", "Аналитик", "Analyst", 20, 20),
          S("Комментарии и выводы", "Commentary and insights", "Аккаунт", "Account manager", 15, 28),
          S("Отправка клиенту", "Send to client", "Аккаунт", "Account manager", 5, 28),
        ],
        20,
        70,
        4,
        8
      ),
      T(
        "dm_brief",
        "Бриф на новую кампанию",
        "New campaign brief",
        "Сбор ТЗ, согласование и постановка задач команде",
        "Collect brief, align stakeholders, create tasks",
        "Запуск брифа на новую рекламную кампанию",
        "New advertising campaign brief intake",
        [
          S("Сбор ТЗ от клиента", "Collect client brief", "Аккаунт", "Account manager", 30, 28),
          S("Согласование стратегии", "Strategy alignment", "Стратег", "Strategist", 20, 30),
          S("Заведение в трекер", "Create tracker tasks", "Проджект", "Project manager", 10, 22),
          S("Постановка задач", "Assign team tasks", "Проджект", "Project manager", 15, 22),
        ],
        12,
        55,
        5,
        4
      ),
      T(
        "dm_content",
        "Контент-план на месяц",
        "Monthly content plan",
        "Идеи, тексты, согласование и публикация",
        "Ideation, copy, approval, publishing",
        "Подготовка и публикация контента",
        "Content preparation and publishing",
        [
          S("Генерация идей", "Idea generation", "Контент-маркетолог", "Content marketer", 15, 22),
          S("Написание текста", "Copywriting", "Копирайтер", "Copywriter", 45, 20),
          S("Согласование с клиентом", "Client approval", "Аккаунт", "Account manager", 10, 28),
          S("Публикация в CMS", "CMS publishing", "SMM", "SMM specialist", 8, 16),
        ],
        40,
        60,
        6,
        6
      ),
      T(
        "dm_landing_leads",
        "Модерация заявок с лендинга",
        "Landing page lead moderation",
        "Проверка, обогащение и передача заявок в CRM",
        "Validate, enrich, and route landing leads",
        "Модерация заявок с лендинга",
        "Landing page lead moderation",
        [
          S("Проверка полноты данных", "Data completeness check", "Оператор", "Operator", 2, 14),
          S("Обогащение контактами", "Contact enrichment", "Оператор", "Operator", 3, 14),
          S("Передача в CRM", "CRM handoff", "Оператор", "Operator", 1, 14),
        ],
        2500,
        85,
        7,
        40
      ),
    ],
  },
  {
    id: "ecommerce",
    name: L("E-commerce и retail", "E-commerce and retail"),
    templates: [
      T(
        "ec_order",
        "Обработка заказа с маркетплейса",
        "Marketplace order processing",
        "Импорт, проверка остатков, сборка и передача в доставку",
        "Import, stock check, pick-pack, handoff to delivery",
        "Обработка заказа с маркетплейса",
        "Marketplace order processing",
        [
          S("Импорт заказа", "Order import", "Оператор", "Operator", 2, 14),
          S("Проверка остатков", "Stock check", "Кладовщик", "Warehouse clerk", 3, 16),
          S("Сборка и упаковка", "Pick and pack", "Кладовщик", "Warehouse clerk", 8, 16),
          S("Передача в доставку", "Delivery handoff", "Логист", "Logistics clerk", 2, 18),
        ],
        3500,
        80,
        4,
        55
      ),
      T(
        "ec_return",
        "Возврат и обмен",
        "Return and exchange",
        "Приём заявки, проверка условий, оформление возврата",
        "Intake, policy check, return processing",
        "Обработка возврата или обмена",
        "Return or exchange processing",
        [
          S("Приём заявки", "Request intake", "Поддержка", "Support agent", 5, 16),
          S("Проверка условий", "Policy validation", "Оператор", "Operator", 6, 16),
          S("Оформление возврата", "Return registration", "Оператор", "Operator", 8, 16),
          S("Возврат на склад", "Warehouse return", "Кладовщик", "Warehouse clerk", 5, 16),
        ],
        450,
        65,
        9,
        18
      ),
      T(
        "ec_card",
        "Обновление карточки товара",
        "Product listing update",
        "Фото, описание, SEO и выгрузка на площадки",
        "Photos, copy, SEO, marketplace upload",
        "Обновление карточки товара",
        "Product listing update",
        [
          S("Подготовка описания", "Description prep", "Контент-менеджер", "Content manager", 25, 20),
          S("SEO и атрибуты", "SEO and attributes", "SEO-специалист", "SEO specialist", 15, 22),
          S("Выгрузка на площадки", "Marketplace upload", "Оператор", "Operator", 12, 14),
        ],
        120,
        70,
        5,
        15
      ),
      T(
        "ec_stock",
        "Сверка остатков",
        "Stock reconciliation",
        "Сверка склада и маркетплейсов, корректировка",
        "Reconcile warehouse vs marketplaces",
        "Сверка остатков склад / маркетплейсы",
        "Warehouse vs marketplace stock reconciliation",
        [
          S("Выгрузка остатков", "Export stock data", "Оператор", "Operator", 10, 14),
          S("Поиск расхождений", "Find discrepancies", "Аналитик", "Analyst", 20, 20),
          S("Корректировка", "Adjust records", "Оператор", "Operator", 15, 14),
        ],
        30,
        75,
        6,
        5
      ),
      T(
        "ec_review",
        "Ответ на отзыв покупателя",
        "Customer review response",
        "Классификация, шаблон ответа, публикация",
        "Classify, draft reply, publish",
        "Обработка отзыва покупателя",
        "Customer review handling",
        [
          S("Классификация отзыва", "Review classification", "Модератор", "Moderator", 2, 14),
          S("Подготовка ответа", "Draft response", "Поддержка", "Support agent", 4, 16),
          S("Публикация ответа", "Publish response", "Модератор", "Moderator", 1, 14),
        ],
        800,
        80,
        3,
        35
      ),
    ],
  },
  {
    id: "b2b_sales",
    name: L("B2B-продажи", "B2B sales"),
    templates: [
      T(
        "b2b_inbound",
        "Входящая заявка → сделка",
        "Inbound lead to deal",
        "Разбор, квалификация, КП и follow-up",
        "Triage, qualify, proposal, follow-up",
        "Обработка входящей B2B-заявки",
        "Inbound B2B lead processing",
        [
          S("Разбор заявки", "Lead triage", "SDR", "SDR", 5, 22),
          S("Квалификация BANT", "BANT qualification", "SDR", "SDR", 12, 22),
          S("Подготовка КП", "Proposal prep", "Менеджер", "Account executive", 25, 35),
          S("Follow-up", "Follow-up", "Менеджер", "Account executive", 8, 35),
        ],
        180,
        60,
        7,
        12
      ),
      T(
        "b2b_proposal",
        "Подготовка коммерческого предложения",
        "Commercial proposal preparation",
        "Сбор данных, расчёт, оформление, согласование",
        "Data gathering, pricing, formatting, approval",
        "Подготовка коммерческого предложения",
        "Commercial proposal preparation",
        [
          S("Сбор данных клиента", "Client data gathering", "Менеджер", "Account executive", 20, 35),
          S("Расчёт стоимости", "Pricing calculation", "Пресейл", "Presales", 30, 30),
          S("Оформление документа", "Document formatting", "Ассистент", "Sales assistant", 25, 18),
          S("Согласование внутри", "Internal approval", "Руководитель", "Sales manager", 10, 40),
        ],
        35,
        55,
        5,
        5
      ),
      T(
        "b2b_pipeline",
        "Еженедельный pipeline review",
        "Weekly pipeline review",
        "Выгрузка CRM, обновление статусов, задачи",
        "CRM export, status updates, action items",
        "Еженедельный обзор воронки продаж",
        "Weekly sales pipeline review",
        [
          S("Выгрузка CRM", "CRM export", "Аналитик", "Analyst", 15, 20),
          S("Обновление статусов", "Status updates", "Менеджер", "Account executive", 30, 35),
          S("Постановка задач", "Create action items", "Руководитель", "Sales manager", 20, 40),
        ],
        4,
        50,
        4,
        3
      ),
      T(
        "b2b_onboard",
        "Онбординг нового клиента",
        "New client onboarding",
        "Договор, счёт, доступы, kick-off",
        "Contract, invoice, access, kick-off",
        "Онбординг нового B2B-клиента",
        "New B2B client onboarding",
        [
          S("Подготовка договора", "Contract preparation", "Юрист", "Legal", 40, 35),
          S("Выставление счёта", "Invoice issuance", "Бухгалтер", "Accountant", 10, 22),
          S("Выдача доступов", "Access provisioning", "Админ", "Admin", 15, 20),
          S("Kick-off встреча", "Kick-off meeting", "Менеджер", "Account executive", 60, 35),
        ],
        8,
        45,
        3,
        2
      ),
      T(
        "b2b_reactivate",
        "Реактивация «уснувших» лидов",
        "Dormant lead reactivation",
        "Сегмент, скрипт, рассылка, фиксация в CRM",
        "Segment, script, outreach, CRM logging",
        "Реактивация неактивных лидов",
        "Dormant lead reactivation",
        [
          S("Сегментация базы", "Database segmentation", "Маркетолог", "Marketer", 20, 20),
          S("Подготовка скрипта", "Script preparation", "Маркетолог", "Marketer", 15, 20),
          S("Рассылка / обзвон", "Outreach campaign", "SDR", "SDR", 5, 22),
          S("Фиксация в CRM", "CRM logging", "SDR", "SDR", 2, 22),
        ],
        500,
        70,
        6,
        30
      ),
    ],
  },
  {
    id: "hr",
    name: L("HR и рекрутинг", "HR and recruiting"),
    templates: [
      T(
        "hr_screen",
        "Скрининг резюме",
        "Resume screening",
        "Парсинг, фильтр, shortlist, приглашение",
        "Parse, filter, shortlist, invite",
        "Скрининг входящих резюме",
        "Inbound resume screening",
        [
          S("Первичный просмотр", "Initial review", "Рекрутер", "Recruiter", 4, 22),
          S("Проверка критериев", "Criteria check", "Рекрутер", "Recruiter", 3, 22),
          S("Shortlist", "Shortlist", "Рекрутер", "Recruiter", 2, 22),
          S("Приглашение на интервью", "Interview invite", "Рекрутер", "Recruiter", 3, 22),
        ],
        400,
        75,
        8,
        35
      ),
      T(
        "hr_hire",
        "Оформление сотрудника",
        "Employee hiring paperwork",
        "Документы, проверка, кадры, доступы",
        "Documents, verification, HRIS, access",
        "Оформление нового сотрудника",
        "New employee onboarding paperwork",
        [
          S("Сбор документов", "Document collection", "HR", "HR specialist", 20, 22),
          S("Проверка комплектности", "Completeness check", "HR", "HR specialist", 15, 22),
          S("Заведение в 1С/кадры", "HRIS entry", "Кадровик", "HR admin", 25, 18),
          S("Выдача доступов", "Access setup", "IT-админ", "IT admin", 20, 25),
        ],
        15,
        65,
        5,
        3
      ),
      T(
        "hr_adapt",
        "Адаптация новичка",
        "New hire adaptation",
        "Чек-лист, встречи, опрос, закрытие",
        "Checklist, meetings, survey, closure",
        "Адаптация сотрудника (2 недели)",
        "Employee adaptation (2 weeks)",
        [
          S("Чек-лист онбординга", "Onboarding checklist", "HR", "HR specialist", 30, 22),
          S("Контроль встреч", "Meeting coordination", "HR", "HR specialist", 20, 22),
          S("Опрос обратной связи", "Feedback survey", "HR", "HR specialist", 10, 22),
        ],
        12,
        50,
        4,
        4
      ),
      T(
        "hr_leave",
        "Учёт отпусков и больничных",
        "Leave and sick day tracking",
        "Заявка, согласование, табель, архив",
        "Request, approval, timesheet, archive",
        "Обработка заявки на отпуск",
        "Leave request processing",
        [
          S("Приём заявки", "Request intake", "HR", "HR specialist", 3, 22),
          S("Согласование руководителем", "Manager approval", "Руководитель", "Manager", 5, 35),
          S("Обновление табеля", "Timesheet update", "Кадровик", "HR admin", 4, 18),
        ],
        80,
        70,
        3,
        12
      ),
      T(
        "hr_timesheet",
        "Ежемесячный табель",
        "Monthly timesheet",
        "Сбор данных, сверка, отправка в бухгалтерию",
        "Collect, reconcile, send to accounting",
        "Закрытие месячного табеля",
        "Monthly timesheet closing",
        [
          S("Сбор данных", "Data collection", "Кадровик", "HR admin", 40, 18),
          S("Сверка с руководителями", "Manager reconciliation", "HR", "HR specialist", 30, 22),
          S("Передача в бухгалтерию", "Handoff to accounting", "Кадровик", "HR admin", 10, 18),
        ],
        1,
        60,
        4,
        1
      ),
    ],
  },
  {
    id: "finance",
    name: L("Финансы и бухгалтерия", "Finance and accounting"),
    templates: [
      T(
        "fin_docs",
        "Обработка первички",
        "Primary document processing",
        "Получение, распознавание, проводка, архив",
        "Receive, OCR, posting, archive",
        "Обработка первичных документов",
        "Primary document processing",
        [
          S("Получение документа", "Document receipt", "Оператор", "Operator", 2, 14),
          S("Распознавание и проверка", "OCR and validation", "Бухгалтер", "Accountant", 5, 22),
          S("Проводка", "Accounting entry", "Бухгалтер", "Accountant", 4, 22),
          S("Архивация", "Archiving", "Оператор", "Operator", 1, 14),
        ],
        2200,
        85,
        6,
        45
      ),
      T(
        "fin_reconcile",
        "Сверка с контрагентом",
        "Counterparty reconciliation",
        "Акт сверки, расхождения, согласование",
        "Statement, discrepancies, alignment",
        "Сверка расчётов с контрагентом",
        "Counterparty reconciliation",
        [
          S("Формирование акта", "Generate statement", "Бухгалтер", "Accountant", 20, 22),
          S("Поиск расхождений", "Find discrepancies", "Бухгалтер", "Accountant", 25, 22),
          S("Согласование", "Alignment", "Финансист", "Finance specialist", 15, 28),
        ],
        40,
        65,
        5,
        6
      ),
      T(
        "fin_payment",
        "Заявка на оплату",
        "Payment request",
        "Инициатор, согласование, платёж, закрытие",
        "Initiator, approval, payment, closure",
        "Обработка заявки на оплату",
        "Payment request processing",
        [
          S("Создание заявки", "Create request", "Инициатор", "Requester", 8, 25),
          S("Согласование", "Approval routing", "Руководитель", "Manager", 5, 35),
          S("Проведение платежа", "Execute payment", "Казначей", "Treasury", 4, 28),
        ],
        350,
        75,
        4,
        20
      ),
      T(
        "fin_close",
        "Закрытие месяца",
        "Month-end close",
        "Выгрузки, сверки, отчёт руководителю",
        "Exports, reconciliations, management report",
        "Закрытие финансового месяца",
        "Financial month-end close",
        [
          S("Выгрузки из систем", "System exports", "Бухгалтер", "Accountant", 60, 22),
          S("Сверки", "Reconciliations", "Бухгалтер", "Accountant", 90, 22),
          S("Отчёт руководителю", "Management report", "Финансист", "Finance specialist", 45, 28),
        ],
        1,
        55,
        3,
        1
      ),
      T(
        "fin_invoice",
        "Выставление счёта клиенту",
        "Client invoicing",
        "Данные из CRM, счёт, отправка, контроль оплаты",
        "CRM data, invoice, send, payment tracking",
        "Выставление счёта клиенту",
        "Client invoice issuance",
        [
          S("Сбор данных из CRM", "CRM data pull", "Менеджер", "Account manager", 5, 30),
          S("Формирование счёта", "Invoice creation", "Бухгалтер", "Accountant", 8, 22),
          S("Отправка клиенту", "Send to client", "Оператор", "Operator", 2, 14),
          S("Контроль оплаты", "Payment follow-up", "Менеджер", "Account manager", 4, 30),
        ],
        280,
        80,
        4,
        18
      ),
    ],
  },
  {
    id: "support",
    name: L("Клиентская поддержка", "Customer support"),
    templates: [
      T(
        "sup_l1",
        "Обработка тикета L1",
        "L1 ticket handling",
        "Классификация, база знаний, ответ, эскалация",
        "Classify, knowledge base, reply, escalate",
        "Обработка обращения L1",
        "L1 support ticket handling",
        [
          S("Классификация", "Classification", "Оператор L1", "L1 agent", 2, 14),
          S("Поиск в базе знаний", "Knowledge base search", "Оператор L1", "L1 agent", 4, 14),
          S("Ответ клиенту", "Customer reply", "Оператор L1", "L1 agent", 6, 14),
          S("Эскалация при необходимости", "Escalation if needed", "Оператор L1", "L1 agent", 2, 14),
        ],
        4500,
        70,
        5,
        45
      ),
      T(
        "sup_followup",
        "Возврат тикета после паузы",
        "Ticket follow-up after pause",
        "Напоминание, статус, закрытие",
        "Reminder, status check, closure",
        "Follow-up по отложенному тикету",
        "Follow-up on paused ticket",
        [
          S("Напоминание клиенту", "Customer reminder", "Оператор", "Agent", 3, 14),
          S("Проверка статуса", "Status check", "Оператор", "Agent", 2, 14),
          S("Закрытие тикета", "Ticket closure", "Оператор", "Agent", 2, 14),
        ],
        600,
        75,
        3,
        35
      ),
      T(
        "sup_user_onboard",
        "Онбординг пользователя продукта",
        "Product user onboarding",
        "Регистрация, обучение, проверка активации",
        "Registration, training, activation check",
        "Онбординг пользователя в продукт",
        "Product user onboarding",
        [
          S("Регистрация аккаунта", "Account registration", "Оператор", "Agent", 8, 14),
          S("Обучающая сессия", "Training session", "CSM", "CSM", 30, 28),
          S("Проверка активации", "Activation check", "CSM", "CSM", 10, 28),
        ],
        120,
        55,
        4,
        10
      ),
      T(
        "sup_nps",
        "Сбор NPS / CSAT",
        "NPS / CSAT collection",
        "Рассылка, сбор, разбор негатива",
        "Send survey, collect, analyze detractors",
        "Сбор и разбор NPS",
        "NPS collection and review",
        [
          S("Рассылка опроса", "Survey dispatch", "Маркетолог", "Marketer", 5, 20),
          S("Сбор ответов", "Response collection", "Аналитик", "Analyst", 10, 20),
          S("Разбор негатива", "Detractor review", "CSM", "CSM", 8, 28),
        ],
        200,
        65,
        2,
        15
      ),
    ],
  },
  {
    id: "legal",
    name: L("Юридический и документооборот", "Legal and document flow"),
    templates: [
      T(
        "leg_contract",
        "Согласование договора",
        "Contract approval",
        "Черновик, правки, юрист, подпись",
        "Draft, revisions, legal review, signature",
        "Согласование договора с контрагентом",
        "Counterparty contract approval",
        [
          S("Подготовка черновика", "Draft preparation", "Юрист", "Legal counsel", 45, 35),
          S("Сбор правок сторон", "Collect redlines", "Юрист", "Legal counsel", 30, 35),
          S("Финальное согласование", "Final approval", "Руководитель", "Executive", 15, 45),
          S("Организация подписи", "Signature coordination", "Ассистент", "Assistant", 20, 18),
        ],
        18,
        45,
        4,
        3
      ),
      T(
        "leg_incoming",
        "Регистрация входящего документа",
        "Incoming document registration",
        "Скан, реестр, маршрут, контроль срока",
        "Scan, registry, routing, deadline control",
        "Регистрация входящего документа",
        "Incoming document registration",
        [
          S("Сканирование", "Scanning", "Секретарь", "Secretary", 3, 14),
          S("Запись в реестр", "Registry entry", "Делопроизводитель", "Records clerk", 5, 16),
          S("Маршрутизация", "Routing", "Делопроизводитель", "Records clerk", 4, 16),
        ],
        350,
        70,
        3,
        25
      ),
      T(
        "leg_docs_request",
        "Запрос документов у контрагента",
        "Counterparty document request",
        "Список, напоминания, проверка, архив",
        "Checklist, reminders, validation, archive",
        "Запрос пакета документов у контрагента",
        "Counterparty document package request",
        [
          S("Формирование списка", "Build checklist", "Юрист", "Legal counsel", 10, 35),
          S("Напоминания", "Reminders", "Ассистент", "Assistant", 5, 18),
          S("Проверка комплектности", "Completeness check", "Юрист", "Legal counsel", 15, 35),
        ],
        25,
        60,
        5,
        4
      ),
    ],
  },
  {
    id: "real_estate",
    name: L("Недвижимость", "Real estate"),
    templates: [
      T(
        "re_lead",
        "Заявка с сайта ЖК",
        "Residential project website lead",
        "Квалификация, подбор, показ, бронь",
        "Qualify, match, showing, booking",
        "Обработка заявки с сайта ЖК",
        "Residential project website lead",
        [
          S("Квалификация клиента", "Client qualification", "Менеджер", "Sales manager", 8, 28),
          S("Подбор варианта", "Unit matching", "Менеджер", "Sales manager", 12, 28),
          S("Организация показа", "Showing coordination", "Менеджер", "Sales manager", 15, 28),
          S("Оформление брони", "Booking processing", "Оператор", "Operator", 10, 16),
        ],
        220,
        60,
        6,
        8
      ),
      T(
        "re_contract",
        "Подготовка договора ДДУ/аренды",
        "DDU / lease contract prep",
        "Анкета, шаблон, согласование, регистрация",
        "Form, template, approval, registration",
        "Подготовка договора ДДУ или аренды",
        "DDU or lease contract preparation",
        [
          S("Сбор анкеты клиента", "Client form intake", "Менеджер", "Sales manager", 20, 28),
          S("Заполнение шаблона", "Template completion", "Юрист", "Legal counsel", 35, 35),
          S("Согласование", "Approval", "Руководитель", "Director", 15, 40),
        ],
        12,
        50,
        4,
        3
      ),
      T(
        "re_handover",
        "Приёмка и передача ключей",
        "Handover and key transfer",
        "Чек-лист, акт, CRM",
        "Checklist, acceptance act, CRM update",
        "Приёмка объекта и передача ключей",
        "Property handover and key transfer",
        [
          S("Чек-лист приёмки", "Handover checklist", "Инженер", "Engineer", 40, 25),
          S("Акт приёма-передачи", "Acceptance act", "Менеджер", "Sales manager", 25, 28),
          S("Обновление CRM", "CRM update", "Оператор", "Operator", 5, 14),
        ],
        8,
        55,
        3,
        2
      ),
    ],
  },
  {
    id: "it_agency",
    name: L("IT и digital-агентства", "IT and digital agencies"),
    templates: [
      T(
        "it_task",
        "Приём задачи от клиента",
        "Client task intake",
        "Тикет, оценка, согласование, спринт",
        "Ticket, estimate, approval, sprint",
        "Приём и оценка задачи от клиента",
        "Client task intake and estimation",
        [
          S("Создание тикета", "Create ticket", "PM", "Project manager", 8, 28),
          S("Оценка трудозатрат", "Effort estimation", "Разработчик", "Developer", 20, 35),
          S("Согласование с клиентом", "Client approval", "PM", "Project manager", 10, 28),
        ],
        80,
        50,
        5,
        10
      ),
      T(
        "it_release",
        "Релиз / деплой",
        "Release / deploy",
        "Чек-лист, staging, prod, уведомление",
        "Checklist, staging, production, notify",
        "Релиз и деплой в production",
        "Production release and deploy",
        [
          S("Чек-лист релиза", "Release checklist", "DevOps", "DevOps engineer", 20, 35),
          S("Деплой на staging", "Staging deploy", "DevOps", "DevOps engineer", 15, 35),
          S("Деплой на prod", "Production deploy", "DevOps", "DevOps engineer", 25, 35),
          S("Уведомление клиента", "Client notification", "PM", "Project manager", 5, 28),
        ],
        12,
        65,
        4,
        4
      ),
      T(
        "it_act",
        "Ежемесячный act / закрывающие",
        "Monthly act / closing docs",
        "Трекер времени, акт, счёт",
        "Time tracker, act, invoice",
        "Ежемесячное закрытие проекта (акт, счёт)",
        "Monthly project closing (act, invoice)",
        [
          S("Выгрузка времени", "Time export", "PM", "Project manager", 15, 28),
          S("Формирование акта", "Act preparation", "Бухгалтер", "Accountant", 20, 22),
          S("Выставление счёта", "Invoice issuance", "Бухгалтер", "Accountant", 10, 22),
        ],
        25,
        70,
        3,
        5
      ),
    ],
  },
  {
    id: "production",
    name: L("Производство и логистика", "Production and logistics"),
    templates: [
      T(
        "prod_purchase",
        "Заявка на закупку",
        "Purchase request",
        "Потребность, согласование, заказ, приёмка",
        "Need, approval, order, receipt",
        "Обработка заявки на закупку",
        "Purchase request processing",
        [
          S("Формирование потребности", "Need definition", "Инициатор", "Requester", 10, 22),
          S("Согласование", "Approval", "Руководитель", "Manager", 8, 30),
          S("Размещение заказа", "Place order", "Закупщик", "Purchaser", 12, 25),
          S("Приёмка на склад", "Warehouse receipt", "Кладовщик", "Warehouse clerk", 8, 16),
        ],
        150,
        65,
        5,
        8
      ),
      T(
        "prod_ship",
        "Планирование отгрузки",
        "Shipment planning",
        "Заказ, резерв, документы, передача ТК",
        "Order, reserve, docs, carrier handoff",
        "Планирование и отгрузка заказа",
        "Order shipment planning",
        [
          S("Подтверждение заказа", "Order confirmation", "Логист", "Logistics clerk", 5, 18),
          S("Резерв на складе", "Stock reservation", "Кладовщик", "Warehouse clerk", 6, 16),
          S("Подготовка документов", "Document prep", "Логист", "Logistics clerk", 10, 18),
          S("Передача транспортной компании", "Carrier handoff", "Логист", "Logistics clerk", 4, 18),
        ],
        800,
        75,
        4,
        30
      ),
      T(
        "prod_defect",
        "Учёт брака / рекламация",
        "Defect / claim handling",
        "Фиксация, анализ, корректирующие действия",
        "Log, analysis, corrective actions",
        "Обработка рекламации по браку",
        "Defect claim handling",
        [
          S("Фиксация инцидента", "Incident logging", "ОТК", "QC inspector", 8, 20),
          S("Анализ причины", "Root cause analysis", "Инженер", "Engineer", 25, 30),
          S("Корректирующие действия", "Corrective actions", "Производство", "Production lead", 20, 25),
        ],
        35,
        55,
        8,
        5
      ),
    ],
  },
];

export const CALCULATOR_TEMPLATE_COUNT = CALCULATOR_SECTORS.reduce(
  (sum, s) => sum + s.templates.length,
  0
);
